doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DB_MAIN_DSN)%'
        types:
            numeric_id: FinizensChallenge\SharedContext\SharedModule\Infrastructure\Persistance\Doctrine\Type\NumericIdType
            uuid: FinizensChallenge\SharedContext\SharedModule\Infrastructure\Persistance\Doctrine\Type\UuidType

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default

        entity_managers:
            default:
                connection: default
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    FinizensChallenge\InvestmentContext\PortfolioModule:
                        is_bundle: false
                        alias: FinizensChallange
                        type: xml
                        prefix: 'FinizensChallenge\InvestmentContext\PortfolioModule\Domain'
                        dir: '%kernel.project_dir%/src/InvestmentContext/PortfolioModule/Infrastructure/Persistance/Doctrine/Mapping'

